version: '3.7'
services:
  verdaccio:
    container_name: verdaccio
    image: verdaccio/verdaccio
    ports:
      - '4873:4873'

  app:
    image: fleek/next-js
    command: sh -c 'npm set registry http://verdaccio:4873 && npm install && npm run build && npm run export'
    working_dir: /workspace
    volumes:
      - './:/workspace'
